import Anthropic from "@anthropic-ai/sdk";
import type { GroundingFacts } from "../domain/grounding.js";
import { feedbackResultSchema } from "../domain/schemas.js";
import {
  FEEDBACK_TOOL_NAME,
  RECEIPT_TOOL_NAME,
  feedbackSystemPrompt,
  feedbackToolDescription,
  feedbackToolSchema,
  feedbackUserPrompt,
  parseReceiptToolResult,
  receiptInstruction,
  receiptToolDescription,
  receiptToolSchema,
} from "./contract.js";
import type { AIProvider, ReceiptImageInput } from "./provider.js";

const receiptTool = {
  name: RECEIPT_TOOL_NAME,
  description: receiptToolDescription,
  input_schema: { ...receiptToolSchema, additionalProperties: false } as Anthropic.Tool["input_schema"],
};

const feedbackTool = {
  name: FEEDBACK_TOOL_NAME,
  description: feedbackToolDescription,
  input_schema: { ...feedbackToolSchema, additionalProperties: false } as Anthropic.Tool["input_schema"],
};

/**
 * Anthropic's OAuth surface expects callers to identify as the CLI, and rejects
 * the request otherwise. This is the documented shape of a subscription-token
 * call — it is the user's own token, generated by `claude setup-token`.
 */
const OAUTH_BETA = "oauth-2025-04-20";
const OAUTH_IDENTITY = "You are Claude Code, Anthropic's official CLI for Claude.";

export type AnthropicAuthMode = "api-key" | "oauth";

export class AnthropicProvider implements AIProvider {
  readonly name: string;
  private readonly client: Anthropic;
  private readonly authMode: AnthropicAuthMode;

  constructor(credential: string, private readonly model: string, authMode: AnthropicAuthMode = "api-key", label?: string) {
    this.authMode = authMode;
    this.name = label ?? (authMode === "oauth" ? "Claude (subscription)" : "Claude");
    this.client = authMode === "oauth"
      ? new Anthropic({ apiKey: null, authToken: credential, defaultHeaders: { "anthropic-beta": OAUTH_BETA } })
      : new Anthropic({ apiKey: credential });
  }

  /** OAuth calls must lead with the CLI identity block; API-key calls must not. */
  private system(prompt?: string): Anthropic.MessageCreateParams["system"] {
    const blocks: Anthropic.TextBlockParam[] = [];
    if (this.authMode === "oauth") blocks.push({ type: "text", text: OAUTH_IDENTITY });
    if (prompt) blocks.push({ type: "text", text: prompt });
    return blocks.length ? blocks : undefined;
  }

  async analyzeReceipt(images: ReceiptImageInput[]) {
    const content: Anthropic.MessageCreateParams["messages"][number]["content"] = [
      ...images.map((image) => ({
        type: "image" as const,
        source: { type: "base64" as const, media_type: image.mimeType, data: image.buffer.toString("base64") },
      })),
      { type: "text" as const, text: receiptInstruction },
    ];
    const response = await withTransientRetry(() => this.client.messages.create({
      model: this.model,
      max_tokens: 2_048,
      system: this.system(),
      messages: [{ role: "user", content }],
      tools: [receiptTool],
      tool_choice: { type: "tool", name: receiptTool.name },
    }));
    this.logUsage("receipt", response.usage.input_tokens, response.usage.output_tokens);
    const block = response.content.find((item) => item.type === "tool_use" && item.name === receiptTool.name);
    if (!block || block.type !== "tool_use") throw new Error("Claude did not return a structured receipt");
    return parseReceiptToolResult(block.input as Record<string, unknown>);
  }

  async generateFeedback(facts: GroundingFacts) {
    const response = await withTransientRetry(() => this.client.messages.create({
      model: this.model,
      max_tokens: 800,
      system: this.system(feedbackSystemPrompt),
      messages: [{ role: "user", content: feedbackUserPrompt(facts) }],
      tools: [feedbackTool],
      tool_choice: { type: "tool", name: feedbackTool.name },
    }));
    this.logUsage("feedback", response.usage.input_tokens, response.usage.output_tokens);
    const block = response.content.find((item) => item.type === "tool_use" && item.name === feedbackTool.name);
    if (!block || block.type !== "tool_use") throw new Error("Claude did not return grounded feedback claims");
    return feedbackResultSchema.parse(block.input);
  }

  private logUsage(operation: string, inputTokens: number, outputTokens: number) {
    console.info(`[receipt-relay] ${this.name} ${operation} usage: ${inputTokens} input, ${outputTokens} output tokens`);
  }
}

async function withTransientRetry<T>(operation: () => Promise<T>, attempts = 3): Promise<T> {
  let lastError: unknown;
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      return await operation();
    } catch (error) {
      lastError = error;
      const status = error instanceof Anthropic.APIError ? error.status : undefined;
      const transient = status === 408 || status === 409 || status === 429 || (status !== undefined && status >= 500);
      if (!transient || attempt === attempts) throw error;
      await new Promise((resolve) => setTimeout(resolve, 250 * 2 ** (attempt - 1)));
    }
  }
  throw lastError;
}
